---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "staging-env.name" . }}
  labels:
    {{- include "staging-env.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "staging-env.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "staging-env.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ template "staging-env.echoServerTag" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: ECHO_SERVER_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ include "staging-env.strictName" . }}-secret
                key: username
